### ISSUE TITLE
Yaml highlighting issue with nested multi line strings

### ISSUE THREAD

**Issue by IvanJosipovic** [danipen/TextMateSharp#60]
**Describe the bug**
Syntax Highlighting appears to be broken after nested multi line strings

```yaml
one: |-
  this is fine
two:
  two: |-
    this is fine
  shouldnt-be-highlighted:
    test:

one: |
  this is fine
two:
  two: |
    this is fine
  shouldnt-be-highlighted:
    test:
 
one: >
  this is fine
two:
  two: >
    this is fine
  shouldnt-be-highlighted:
    test:
  
one: >-
  this is fine
two:
  two: >-
    this is fine
  shouldnt-be-highlighted:
    test:
```

**To Reproduce**
1. Load the Yaml above

**Expected behavior**
Lines following a nested multi line string should be highlighted correctly

**Screenshots**
Left is VS Code, right is AvaloniaEdit
![image](https://github.com/danipen/TextMateSharp/assets/9521987/526753eb-6594-4b08-a847-7ca195e6a71d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - TextMateSharp Version="1.0.56"
 - Avalonia.AvaloniaEdit Version="11.0.6"
 - AvaloniaEdit.TextMate Version="11.0.6"
